apiVersion: v1
kind: ServiceAccount
metadata:
  name: simpleapi  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bbox  
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplebbox  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplebbox
  template:
    metadata:
      labels:
        app: simplebbox
    spec:          
      containers:
      - name: simplebbox
        image: governmentpaas/curl-ssl
        command: ["/bin/sleep", "30d"]
        imagePullPolicy: IfNotPresent        
      serviceAccountName: bbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapi
  template:
    metadata:
      labels:
        app: simpleapi
    spec:      
      serviceAccountName: simpleapi     
      containers:
      - name: simpleapi
        image: stephaneey/simpleapi:dev       
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapisvc  
  labels:
    app: simpleapi
    service: simpleapisvc
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: simpleapi